name: Update Energy Data
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *' # Atualiza a cada 5 minutos

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      
      - name: Run updater
        run: |
          mkdir -p data
          go run update.go &
          sleep 300 # Executa por 5 minutos
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true